In [1]:
import numpy as np


In [2]:
X = np.array(np.random.randn(15, 2))

In [14]:
X

array([[ 0.88074906,  0.26046596],
       [ 3.07002388,  0.00564112],
       [ 0.56029125,  0.29783878],
       [ 1.2095303 ,  0.53209668],
       [-1.73096676, -0.48814427],
       [ 0.79416336, -0.92849887],
       [ 0.52084946, -0.40891087],
       [ 0.33827351, -1.11370803],
       [ 1.08731588,  1.45764624],
       [ 0.60423698,  0.51627008],
       [-0.28429971,  0.36659811],
       [-1.06649243,  0.88961116],
       [-0.50056678,  0.11116946],
       [-1.89270371, -0.20443088],
       [-0.36685246, -0.58278473]])

In [18]:
for row in X:
    print(np.linalg.norm(row))

0.9184560025189462
3.0700290610541865
0.6345346536106058
1.3213971491036296
1.7984801247980187
1.2218042400469245
0.6621874811907176
1.1639478255094808
1.8185126839981367
0.794756015673888
0.46391863754436524
1.388817522525143
0.5127628568305694
1.9037119887575633
0.6886354434775586


In [13]:
X[0:X.shape[0],0]

array([ 0.88074906,  3.07002388,  0.56029125,  1.2095303 , -1.73096676,
        0.79416336,  0.52084946,  0.33827351,  1.08731588,  0.60423698,
       -0.28429971, -1.06649243, -0.50056678, -1.89270371, -0.36685246])

In [15]:
for featureset in X[:
    print(featureset)

[0.88074906 0.26046596]
[3.07002388 0.00564112]
[0.56029125 0.29783878]
[1.2095303  0.53209668]
[-1.73096676 -0.48814427]
[ 0.79416336 -0.92849887]
[ 0.52084946 -0.40891087]
[ 0.33827351 -1.11370803]
[1.08731588 1.45764624]
[0.60423698 0.51627008]
[-0.28429971  0.36659811]
[-1.06649243  0.88961116]
[-0.50056678  0.11116946]
[-1.89270371 -0.20443088]
[-0.36685246 -0.58278473]


In [6]:
X[0:3]

array([[0.88074906, 0.26046596],
       [3.07002388, 0.00564112],
       [0.56029125, 0.29783878]])

In [8]:
centroids = []
centroids.append(X[0:2])

In [9]:
centroids

[array([[0.88074906, 0.26046596],
        [3.07002388, 0.00564112]])]

In [10]:
np.array(centroids)

array([[[0.88074906, 0.26046596],
        [3.07002388, 0.00564112]]])

In [19]:
points = np.vstack(((np.random.randn(150, 2) * 0.75 + np.array([1, 0])),
                  (np.random.randn(50, 2) * 0.25 + np.array([-0.5, 0.5])),
                  (np.random.randn(50, 2) * 0.5 + np.array([-0.5, -0.5]))))

In [21]:
points.shape

(250, 2)